name: Build ChromeOS ARCVM Kernel

on:
  workflow_call:
  workflow_dispatch:

env:
  git_tag: chromeos-5.10-arcvm

jobs:

  build:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)

    strategy:
      matrix:
        include:

          - ARCH: x86_64
            kernel_image_name: bzImage
            build_config: build.config.gki.x86_64
            defconfig: x86_64_arcvm_defconfig

          - ARCH: arm64
            kernel_image_name: Image
            build_config: build.config.gki.aarch64
            defconfig: arm64_arcvm_defconfig


    name: Build ChromeOS ARCVM Kernel ${{ matrix.ARCH }}

    runs-on: ubuntu-22.04


    env:
      LTO: thin
      ROOT_DIR: /
      KERNEL_DIR: ${{ github.workspace }}/kernel


    steps:


    - name: Install dependencies
      run: |

        sudo apt update

        sudo apt install -y \
        bc \
        bison \
        build-essential \
        ca-certificates \
        flex \
        git \
        gnupg \
        libelf-dev \
        libssl-dev \
        libncurses-dev \
        binutils-aarch64-linux-gnu \
        gcc-aarch64-linux-gnu \
        gzip \
        rsync \
        python3 \
        device-tree-compiler


        sudo ln -sf python3 /usr/bin/python


        export LLVM_VERSION=14


        wget https://apt.llvm.org/llvm.sh

        chmod +x llvm.sh

        sudo ./llvm.sh $LLVM_VERSION

        rm llvm.sh


        for tool in clang clang++ ld.lld llvm-ar llvm-nm llvm-strip llvm-objcopy llvm-readelf llvm-objdump
        do
          sudo ln -sf /usr/bin/${tool}-${LLVM_VERSION} /usr/bin/${tool}
        done



    - name: Checkout KernelSU

      uses: actions/checkout@v5

      with:

        repository: tiann/KernelSU

        path: KernelSU

        fetch-depth: 0



    - name: Clone ChromeOS kernel

      run: |

        git clone \
        https://chromium.googlesource.com/chromiumos/third_party/kernel.git \
        -b ${{ env.git_tag }} \
        --depth=1 \
        kernel



    - name: Kernel version

      working-directory: kernel

      run: |

        VERSION=$(grep '^VERSION =' Makefile | awk '{print $3}')

        PATCHLEVEL=$(grep '^PATCHLEVEL =' Makefile | awk '{print $3}')

        SUBLEVEL=$(grep '^SUBLEVEL =' Makefile | awk '{print $3}')


        echo "Linux version $VERSION.$PATCHLEVEL.$SUBLEVEL"

        echo "version=$VERSION.$PATCHLEVEL.$SUBLEVEL" >> $GITHUB_ENV



    - name: Integrate KernelSU

      working-directory: kernel

      run: |

        echo "[+] Installing KernelSU"


        KERNEL_ROOT=$GITHUB_WORKSPACE/kernel


        mkdir -p \
        $KERNEL_ROOT/drivers/kernelsu


        cp -r \
        $GITHUB_WORKSPACE/KernelSU/kernel/* \
        $KERNEL_ROOT/drivers/kernelsu/


        echo "[+] Add Makefile"


        grep -q kernelsu drivers/Makefile || \
        echo 'obj-$(CONFIG_KSU) += kernelsu/' >> drivers/Makefile



        echo "[+] Add Kconfig"


        grep -q kernelsu drivers/Kconfig || \
        sed -i '/endmenu/i source "drivers/kernelsu/Kconfig"' drivers/Kconfig



        echo "[+] Fix ChromeOS missing X86_FEATURE_INDIRECT_SAFE"


        FILE=$KERNEL_ROOT/drivers/kernelsu/core/init.c


        sed -i \
        's/boot_cpu_has(X86_FEATURE_INDIRECT_SAFE)/0/g' \
        $FILE



        echo "[+] Remove dirty suffix"


        sed -i 's/-dirty//g' \
        scripts/setlocalversion



        echo "[+] KernelSU done"



    - name: Build kernel

      working-directory: kernel

      env:

        KERNEL_IMAGE_NAME: ${{ matrix.kernel_image_name }}

        ARCH: ${{ matrix.ARCH }}


      run: |


        set -e



        set -a

        source ${{ matrix.build_config }}

        set +a



        export DEFCONFIG=${{ matrix.defconfig }}



        make \
        LLVM=1 \
        LLVM_IAS=1 \
        DEPMOD=depmod \
        DTC=dtc \
        O=${PWD} \
        mrproper



        make \
        LLVM=1 \
        LLVM_IAS=1 \
        DEPMOD=depmod \
        DTC=dtc \
        O=${PWD} \
        ${DEFCONFIG}



        scripts/config \
        --file .config \
        -e LTO_CLANG \
        -d LTO_NONE \
        -e LTO_CLANG_THIN \
        -d LTO_CLANG_FULL \
        -e KSU



        make \
        LLVM=1 \
        LLVM_IAS=1 \
        DEPMOD=depmod \
        DTC=dtc \
        O=${PWD} \
        -j$(nproc) \
        ${KERNEL_IMAGE_NAME} \
        modules \
        prepare-objtool



        ls -lh \
        arch/${ARCH}/boot



        echo \
        "file_path=${PWD}/arch/${ARCH}/boot/${KERNEL_IMAGE_NAME}" \
        >> $GITHUB_ENV



    - name: Upload kernel

      uses: actions/upload-artifact@v5

      with:

        name: kernel-ARCVM-${{ matrix.ARCH }}-${{ env.version }}

        path: ${{ env.file_path }}
