名称：构建内核 - ChromeOS ARCVM
关于：
  workflow_call：
  workflow_dispatch：

环境：
  git_tag： chromeos-5.10-arcvm

职位：
  构建：
    如果：github.event_name ！= 'pull_request' ||（github.event_name == 'pull_request' & ！github.event.pull_request.draft）
    策略：
      矩阵：
        包括：
          - ARCH：x86_64
            kernel_image_name：bzImage
            build_config：build.config.gki.x86_64
            defconfig：x86_64_arcvm_defconfig
          - 建筑：ARM64
            kernel_image_name：图片
            build_config： build.config.gki.aarch64
            defconfig：arm64_arcvm_defconfig

    名称：构建 ChromeOS ARCVM 内核
    运行时间：Ubuntu-22.04
    环境：
      LTO：薄弱
      ROOT_DIR：/
      KERNEL_DIR： ${{ github.workspace }}/kernel

    步骤：
      - 名称：安装构建工具
        运行：|
          Sudo APT获取更新
          sudo apt-get install -y --no-install-recommends bc \
          Bison Build-Essential CA-Certificates Flex Git GNUPG \
          Libelf-dev libssl-dev LSB-release software-properties-common wget \
          libncurses-dev binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu nuget gzip \
          rsync python3 device-tree-compiler
          sudo LN -s --force python3 /usr/bin/Python
          导出 LLVM_VERSION=14
          WGET https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh $LLVM_VERSION
          rm ./llvm.sh
          sudo LN -s --force /usr/bin/clang-$LLVM_VERSION /usr/bin/clang
          sudo LN -s --force /usr/bin/ld.lld-$LLVM_VERSION /usr/bin/ld.lld
          sudo LN -s --force /usr/bin/LLVM-objdump-$LLVM_VERSION /usr/bin/llvm-objdump
          sudo LN -s --force /usr/bin/llvm-ar-$LLVM_VERSION /usr/bin/llvm-ar
          sudo LN -s --force /usr/bin/LLVM-nm-$LLVM_VERSION /usr/bin/llvm-nm
          sudo LN -s --force /usr/bin/llvm-strip-$LLVM_VERSION /usr/bin/llvm-strip
          sudo LN -s --force /usr/bin/llvm-objcopy-$LLVM_VERSION /usr/bin/llvm-objcopy
          sudo LN -s --force /usr/bin/llvm-readelf-$LLVM_VERSION /usr/bin/llvm-readelf
          sudo LN -s --force /usr/bin/clang++-$LLVM_VERSION /usr/bin/clang++
      - 名称：查看KernelSU
        用途：行动/checkout@v5
        与：
          仓库：tiann/KernelSU
          路径：KernelSU
          取水深度：0

      - 名称：设置内核源代码
        运行：|
          git clone https://chromium.googlesource.com/chromiumos/third_party/kernel.git -b ${{ env.git_tag }} --depth=1
          # === 以下两行为针对报错的修复 ===
          echo "[+] 修复 X86_FEATURE_INDIRECT_SAFE 未定义报错"
          echo "#define X86_FEATURE_INDIRECT_SAFE (18*32+25)" >> kernel/arch/x86/include/asm/cpufeatures.h
          # ================================

      - 名称：从 Makefile 提取版本
        工作目录：kernel
        运行：|
          VERSION=$（grep -E '^VERSION = ' Makefile | awk '{print $3}'）
          PATCHLEVEL=$（grep -E '^PATCHLEVEL = ' Makefile | awk '{print $3}'）
          SUBLEVEL=$（grep -E '^SUBLEVEL = ' Makefile | awk '{print $3}'）
          echo “ChromeOS ARCVM Linux 内核版本：$VERSION.$PATCHLEVEL.$SUBLEVEL”
          echo “version=$VERSION.$PATCHLEVEL.$SUBLEVEL” >> $GITHUB_ENV
      - 名称：设置KernelSU
        工作目录：kernel
        运行：|
          echo “[+] KernelSU 设置”
          KERNEL_ROOT=$GITHUB_WORKSPACE/kernel
          回声 “[+] KERNEL_ROOT： $KERNEL_ROOT”
          echo “[+] 将 KernelSU 驱动复制到 $KERNEL_ROOT/drivers”
          inn -sf $GITHUB_WORKSPACE/KernelSU/kernel $KERNEL_ROOT/drivers/kernelsu
          echo “[+] 将 KernelSU 驱动添加到 Makefile”
          DRIVER_MAKEFILE=$KERNEL_ROOT/drivers/Makefile
          DRIVER_KCONFIG=$KERNEL_ROOT/drivers/Kconfig
          grep -q “kernelsu” “$DRIVER_MAKEFILE” ||printf “\nobj-\$（CONFIG_KSU） += kernelsu/\n” >> “$DRIVER_MAKEFILE”
          grep -q “kernelsu” “$DRIVER_KCONFIG” ||sed -i “/endmenu/i\\source \”drivers/kernelsu/Kconfig\“” “$DRIVER_KCONFIG”
          echo “[+] 应用 KernelSU 补丁”
          cd $KERNEL_ROOT && git apply $GITHUB_WORKSPACE/KernelSU/.github/patches/5.10/*.patch ||回声 “[-] 找不到补丁”
          echo “[+] Patch script/setlocalversion”
          sed -i 's/-dirty//g' $KERNEL_ROOT/scripts/setlocalversion
          echo “[+] KernelSU 设置完成。”
          cd $GITHUB_WORKSPACE/KernelSU
          KSU_VERSION=$（（$（git rev-list --count HEAD） + 10200））
          echo “KernelSU 版本： $KSU_VERSION”
          echo “kernelsu_version=$KSU_VERSION” >> $GITHUB_ENV
      - 名称：构建内核
        工作目录：kernel
        环境：
          KERNEL_IMAGE_NAME： ${{ matrix.kernel_image_name }}
          ARCHs： ${{ matrix.arch }}
        运行：|
          集合 -a && 。${{ matrix.build_config }};集合+a
          export DEFCONFIG=${{ matrix.defconfig }}
          如果 [ ！ -z ${{ vars.EXPECTED_SIZE }} ] & [ ！ -z ${{ vars.EXPECTED_HASH }} ];则
          export KSU_EXPECTED_SIZE=${{ vars.EXPECTED_SIZE }}
          export KSU_EXPECTED_HASH=${{ vars.EXPECTED_HASH }}
          Fi
          make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=${PWD} mrproper
          make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=${PWD} ${DEFCONFIG} < /dev/null
          scripts/config --file .config -e LTO_CLANG -d LTO_NONE -e LTO_CLANG_THIN -d LTO_CLANG_FULL -e THINLTO
          make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=${PWD} -j$（nproc） ${KERNEL_IMAGE_NAME} modules prepare-objtool
          ls -l -h ${PWD}/arch/${ARCH}/boot
          echo “file_path=${PWD}/arch/${ARCH}/boot/${KERNEL_IMAGE_NAME}” >> $GITHUB_ENV
      - name： Upload kernel-ARCVM-${{ matrix.arch }}-${{ env.version }}
        用途：动作/上传-artifact@v5
        与：
          name： kernel-ARCVM-${{ matrix.arch }}-${{ env.version }}
          路径：“${{ env.file_path }}”
